CREATE TABLE MessageRead(
    Id INT IDENTITY(1, 1),
    UserId INT NOT NULL,
    MessageId INT NOT NULL,
    ReadAt DATETIME NOT NULL,
    CONSTRAINT UserId_FK FOREIGN KEY(UserId) REFERENCES Users(Id),
    CONSTRAINT MessageId_FK FOREIGN KEY(MessageId) REFERENCES Messages(Id)
);